WEB/routes/auth.py
from flask import Blueprint, render_template, flash, request, redirect, url_for, session
from WEB.model import Customers, Category
from werkzeug.security import generate_password_hash, check_password_hash
from WEB.ext import db, generate_csrf_token, validate_csrf_token, login_user, logout_user, current_user, login_required
from WEB.api_scraper.category import get_cached_category_links
auth = Blueprint("auth", __name__, url_prefix="/")


@auth.route("/")
def overview():
    data = []
    url = "https://www.jumia.com.ng/?gad_source=1&gclid=Cj0KCQiA0MG5BhD1ARIsAEcZtwQEskgvscM7H4ALDZOiv89BdT_H3jAGH_0xLTBsqUHW588mqdKvzFIaAhySEALw_wcB"
    get_cached_category_links(url)
    category = Category.query.all()
    for product in category:
        data.append(
            {
                'name':product.name,
                'link':product.link
            }
        )
    return render_template("overview.html", current_user=current_user, data=data)


    
    
@auth.route("/login", methods = ['POST', 'GET'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("home.index"))
    
    
    if request.method == "POST":
        session['username'] = username = request.form.get("username")
        password = request.form.get('password')
        check_user = Customers.query.filter_by(username=username).first()
        username = username
        if check_user:
            if check_password_hash(check_user.password, password):
                flash("logged-in successfully")
                login_user(check_user)
                return redirect(url_for("home.index"))
            else:
                flash("incorrect password")
                return redirect(url_for("auth.login"))
        flash("no user found")
        return redirect(url_for("auth.login"))
    try:
        return render_template("loginform.html", username=session['username'])
    except KeyError:
        return render_template("loginform.html", username='')




@auth.route('/register', methods = ['POST', 'GET'])
def register():
    
    if current_user.is_authenticated:
        return redirect(url_for("home.index"))
    
    
    username = ''
    email = ''
    phone = ''
    email_ext = ['gmail.com', 'hotmail.com' ,'outlook.com']
    if request.method == "POST":
        token = request.form.get("csrf_token")
        if validate_csrf_token(token=token):
            session["username"] = username = request.form.get("username")
            session["email"] = email = request.form.get("email")
            session["phone"] = phone = request.form.get("phone")
            password = request.form.get('password')
            validate_email = True if email.split('@')[1] in email_ext else False
            check_user_email = Customers.query.filter_by(email=email).first()
            check_user_name = Customers.query.filter_by(username=username).first()
            if len(username)<2:
                flash("Username too short")
                return redirect(url_for("auth.register"))
            elif not validate_email:
                flash("invalid email, email should be either gmail.com, hotmail.com or outlook.com")
                return redirect(url_for("auth.register"))
            elif len(phone) < 10 or len(phone)>12 :
                flash("number must be 11-digts")
                return redirect(url_for("auth.register"))
            elif len(password)< 6:
                flash("password too short")
                return redirect(url_for("auth.register"))
            
            if not check_user_name:
                if not check_user_email:
                    add_user = Customers(
                        username=username,
                        email=email,
                        password=generate_password_hash(password),
                        phone=phone
                    )
                    db.session.add(add_user)
                    db.session.commit()
                    flash("registered successfully")
                    
                    login_user(add_user)
                    
                    return redirect(url_for("auth.login"))
                else:
                    flash("email already used")
                    return redirect(url_for('auth.register'))
            else:
                flash("username already used")
                return redirect(url_for('auth.register'))               
        else:
            flash("csrf token expired")
    try:

        return render_template("regform.html", csrf_token=generate_csrf_token(), username=session['username'], email=session['email'], phone=session['phone'])
    except KeyError:
        return render_template("regform.html", csrf_token=generate_csrf_token(), username='', email='', phone='')


@auth.route('/logout')
@login_required
def logout():
    session.clear()
    logout_user()
    flash("logged out successfully")
    return redirect(url_for("auth.login"))

WEB/routes/home.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, session
from WEB.ext import login_required, current_user, allowd_file
from WEB.model import Customers, CategoryProduct, Category, PaymentRecord
from WEB.config import Config
from WEB.ext import db
import os
from werkzeug.utils import secure_filename
from WEB.api_scraper.category import get_product_cache_details, get_searched_product
import json
from random import choice

home = Blueprint("home", __name__, url_prefix="/home")

@home.route("/", methods= ['POST', 'GET'])
@login_required
def index():
    choices = ['phones', 'fashion', "toys", 'baby stuff', "supermarket", "shirts"]
    value = choice(choices)
    if request.method == 'POST':
        value = request.form['value']    
        return redirect(url_for("home.home_loading", value=value))
    
    if "value" in session:
        value = session['value']
    output = get_searched_product(value=value)
    return render_template("search.html", output=output, value=value, output_length=len(output),show_search_bar=True)


@home.route("/loading/home/<value>")
def home_loading(value):
    session['value'] = value
    return render_template("home_loadAnimation.html")




@home.route("/profile", methods = ['POST', 'GET'])
@login_required
def view_profile():
    config = Config()
    get_user = Customers.query.get(current_user.id)
    os.makedirs(config.UPLOAD_FOLDER, exist_ok=True)
    if request.method == 'POST':
        username = request.form['username']
        email = request.form['email']
        phone = request.form['phone']
        file = request.files['profile_photo']
        
        if file and allowd_file(file.filename):
            filename = secure_filename(file.filename)
            file_path = os.path.join(config.UPLOAD_FOLDER, filename).replace("\\", '/')
            file.save(file_path)
            
            if username != '':
                get_user.username = username 
            elif email == '':
                get_user.email = email
            elif phone == '':
                get_user.phone = phone
            
            get_user.profile_image = file_path
            db.session.commit()
            flash("updated...")
            return redirect(url_for('home.view_profile'))
        else:
            if username != '':
                get_user.username = username 
            elif email == '':
                get_user.email = email
            elif phone == '':
                get_user.phone = phone
            db.session.commit()
            flash("updated...")
            return redirect(url_for('home.view_profile'))
    photo_data = None    
    if get_user.profile_image:
        photo_data = get_user.profile_image
    try:
        if photo_data != None:
            return render_template("profile.html", username=get_user.username, 
                           email=get_user.email, 
                           phone=get_user.phone, photo =photo_data.split('/static/')[1])
        return render_template("profile.html", username=get_user.username, 
                           email=get_user.email, 
                           phone=get_user.phone, photo='empty')
    except:
        if photo_data != None:
            return render_template("profile.html", username=get_user.username, 
                           email=get_user.email, 
                           phone=get_user.phone, photo =photo_data.split('/static/')[1])
        return render_template("profile.html", username=get_user.username, 
                           email=get_user.email, 
                           phone=get_user.phone, photo ='empty')
        
        
        
@home.route('/delete')
@login_required
def delete_dp():
    get_user = Customers.query.get(current_user.id)
    get_user.profile_image = None
    db.session.commit()
    flash("profile image deleted successfully")
    return redirect(url_for("home.view_profile"))
    
@home.route('/history')
@login_required
def history():
    get_record = PaymentRecord.query.filter_by(customer_id=current_user.id).order_by(PaymentRecord.date).all()
    return render_template("history.html",get_record=get_record)

WEB/routes/service.py
from flask import Blueprint, render_template, session, redirect, url_for, flash, request
from WEB.model import Category, CategoryProduct, Product, Searched_Product, CartList, Customers, PaymentRecord
from WEB.ext import login_required, current_user, db
from WEB.api_scraper.category import get_product_cache_details, get_particular_product_detail, get_searched_product, get_particular_product_search
import json

service = Blueprint("service", __name__, url_prefix="/products")

@service.route("/<name>")
def products(name):
    data = []
    get_pproduct_link = Category.query.filter_by(name=name).first()
    if get_pproduct_link:
        link = get_pproduct_link.link
        category_id = get_pproduct_link.id
        get_product_cache_details(link, category_id=category_id)
        prodt = CategoryProduct.query.filter_by(category_id=category_id).all()
        for items in prodt:
            data.append({
                "heading": items.heading,
                "discription": items.description,
                "image_url":items.img_url,
                "info_url":items.info_url,
                "price": items.price,
                "previous_price":items.previous_price,
                "discount": items.discount
            })
    heading = []
    for num in range(len(data)):
        head = data[num]['heading']
        if head in heading:
            pass
        else:
            heading.append(
                head
            )
    heading_length = len(heading)
    data_length = len(data)
    
    return render_template("service.html",data=data,
                           heading_length=heading_length,
                           data_length=data_length,
                           heading=heading
                           )
    
@service.route('/loading/<product>')
def loading(product):
    session['product'] = product.replace("_", "/")
    return render_template("load.html")



@service.route('/loading/<name>/<input_>')
def search_loading(name, input_):
    session['name'] = name.replace("_", "/")
    session['input'] = input_
    return render_template("default_loading.html")


@service.route("/product_item")
def particular_product():
    get_product = CategoryProduct.query.filter_by(description=session['product']).first()
    if get_product:
        get_particular_product_detail(get_product.info_url,product_id=get_product.id)
        output = Product.query.filter_by(categoryProduct_id=get_product.id).first()
        return render_template("product.html",output=output,current_user=current_user)
    return "no product found"





@service.route('/searched_product-item')
def particular_searched_product():
    outputList = get_searched_product(session['input'])
    url = 'https://www.jumia.com.ng'
    for items in range(len(outputList)):
        if session['name'] == outputList[items]['name']:
            url += outputList[items]['details']
    get_particular_product_search(url, session["input"])
    output= Searched_Product.query.filter_by(name=session['name']).first()
    return render_template("product.html",output=output,current_user=current_user)


@service.route("/view-cart")
@login_required
def view_cart():
    cart = CartList.query.filter_by(customers_id= current_user.id).all()
    return render_template("view_cart.html",cart=cart)


@service.route("/add-cart/<pname>/<price>")
@login_required
def add_product(pname, price):
    session['pname'] = pname.replace("_", "/")
    check_1 = Product.query.filter_by(name=session['pname']).first()
    check_2 = Searched_Product.query.filter_by(name=session['pname']).first()
    if check_1:
        session['image'] = check_1.img_url
    elif check_2:
        session['image'] = check_2.img_url
        
    cart = CartList.query.filter_by(product_name=session['pname']).first()
    if not cart:
        cart = CartList(
            product_name =session['pname'],
            price = price,
            customers_id = current_user.id,
            image = session['image']
        )
        db.session.add(cart)
        db.session.commit()
        flash("product added successfully")
        return redirect(url_for("service.view_cart"))
    
    flash("product already in cart")
    return redirect(url_for("service.view_cart"))


@service.route("/delete-product-fromCart/<ID>")
@login_required
def delete_product(ID):
    get_product = CartList.query.get(ID)
    product_name = get_product.product_name
    db.session.delete(get_product)
    db.session.commit()
    flash(f"{product_name} removed from cart list successfully")
    return redirect(url_for("service.view_cart"))


@service.route('/view-product/<name>')
@login_required
def view_product(name):
    session['name'] = name.replace("_", "/")
    check_1 = Product.query.filter_by(name=session['name']).first()
    check_2 = Searched_Product.query.filter_by(name=session['name']).first()
    if check_1:
        output = check_1
    elif check_2:
        output = check_2
    return render_template("product.html",output=output,current_user=current_user)
    
    
@service.route('/buy-now/<tobuy>', methods=['POST', 'GET'])
@login_required
def buy(tobuy):
    price = ''
    img = ''
    session['tobuy'] = tobuy.replace("_", "/")
    check_1 = Product.query.filter_by(name=session['tobuy']).first()
    check_2 = Searched_Product.query.filter_by(name=session['tobuy']).first()
    if check_1:
        price = check_1.price
        img = check_1.img_url
    elif check_2:
        price = check_2.price
        img = check_2.img_url
        
    get_user = Customers.query.get(current_user.id)
    if request.method == "POST":
        address = request.form["shipping-address"]
        payment_method = request.form.get('payment-method')
        
        payment = PaymentRecord(
            product_name = tobuy, 
            price=price,
            payment_method=payment_method,
            address=address,
            customer_id=current_user.id
            
        )
        db.session.add(payment)
        db.session.commit()
        flash("payment proceedure completed")
        get_product = CartList.query.filter_by(product_name=session['tobuy']).first()
        try:
            db.session.delete(get_product)
            db.session.commit()
            return redirect(url_for("service.view_cart"))
        except Exception as e:
            return redirect(url_for("home.index"))
    return render_template("buynow.html", name=get_user.username, email=get_user.email, product=tobuy, price=price,image=img)

WEB/templates/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{% endblock %}</title>

  <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  {% block link %}

  {% endblock %}
</head>
<body>
  <!-- Fixed Header -->
  <header class="p-2 mb-0.5 border-bottom ">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start max-width: 500px;">
        <!-- Logo Section -->
        <a href="/" class="logo-container">
          <img src="{{ url_for('static', filename='images/logo.webp') }}" alt="Logo" class="logo">
          <div class="logo-text">eCommerce 🛒</div>
        </a>

        {%if current_user.is_authenticated%}
        <!-- Navigation Links -->
         <!-- if user authenticated -->
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="{{url_for('home.index')}}" class="nav-link px-2 link-body-emphasis">Overview <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-speedometer2" viewBox="0 0 16 16">
            <path d="M8 4a.5.5 0 0 1 .5.5V6a.5.5 0 0 1-1 0V4.5A.5.5 0 0 1 8 4M3.732 5.732a.5.5 0 0 1 .707 0l.915.914a.5.5 0 1 1-.708.708l-.914-.915a.5.5 0 0 1 0-.707M2 10a.5.5 0 0 1 .5-.5h1.586a.5.5 0 0 1 0 1H2.5A.5.5 0 0 1 2 10m9.5 0a.5.5 0 0 1 .5-.5h1.5a.5.5 0 0 1 0 1H12a.5.5 0 0 1-.5-.5m.754-4.246a.39.39 0 0 0-.527-.02L7.547 9.31a.91.91 0 1 0 1.302 1.258l3.434-4.297a.39.39 0 0 0-.029-.518z"/>
            <path fill-rule="evenodd" d="M0 10a8 8 0 1 1 15.547 2.661c-.442 1.253-1.845 1.602-2.932 1.25C11.309 13.488 9.475 13 8 13c-1.474 0-3.31.488-4.615.911-1.087.352-2.49.003-2.932-1.25A8 8 0 0 1 0 10m8-7a7 7 0 0 0-6.603 9.329c.203.575.923.876 1.68.63C4.397 12.533 6.358 12 8 12s3.604.532 4.923.96c.757.245 1.477-.056 1.68-.631A7 7 0 0 0 8 3"/>
          </svg></a></li>
          <li><a href="{{url_for('auth.overview')}}" class="nav-link px-2 link-body-emphasis">Category</a></li>

          
          <li><a href="{{url_for('service.view_cart')}}" class="nav-link px-2 link-body-emphasis">Cart <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
            <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5M3.102 4l1.313 7h8.17l1.313-7zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4m7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4m-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2m7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2"/>
          </svg></a>
          
          </li>
        </ul>

        <!-- Search Form -->
         {%if show_search_bar%}
        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search" method="post"  >
          <input type="hidden" name="search" value="search">
          <input type="search" class="form-control" name="value" placeholder="Search..." aria-label="Search" value="{{value}}">
        </form>
        {%endif%}

        <!-- Profile Dropdown -->
         
        <div class="dropdown text-end">
          <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            {%if current_user.is_authenticated%}
            {%if current_user.profile_image %}
            <img src="{{url_for('static', filename = current_user.profile_image.split('/static/')[1])}}" alt="Profile" width="32" height="32" class="rounded-circle" style="object-fit: cover;">
            {%else%}
            <img src="{{url_for('static', filename = 'images/download.png')}}" alt="Profile" width="32" height="32" class="rounded-circle" style="object-fit: cover;">
            {%endif%}
            {%else%}
            <img src="{{url_for('static', filename = 'images/download.png')}}" alt="Profile" width="32" height="32" class="rounded-circle" style="object-fit: cover;">
            {%endif%}
            
          </a>
        

          <!-- if user authenticated -->
          <ul class="dropdown-menu text-small">
            <!-- <li><a class="dropdown-item" href="#">New project...</a></li> -->
            <li><a class="dropdown-item" href="{{url_for('home.history')}}">History</a></li>
            <li><a class="dropdown-item" href="{{url_for('home.view_profile')}}">Profile <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-lines-fill" viewBox="0 0 16 16">
              <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6m-5 6s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zM11 3.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1-.5-.5m.5 2.5a.5.5 0 0 0 0 1h4a.5.5 0 0 0 0-1zm2 3a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1zm0 3a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1z"/>
            </svg></a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{{url_for('auth.logout')}}">Sign out</a></li>
            <li></li>
          </ul>
          {%endif%}
        </div>
      </div>
    </div>
  </header>

  <!-- Notification Container -->
  <div id="notification-container" class="position-fixed top-0 start-50 translate-middle-x">
    {% for msg in get_flashed_messages() %}
      <p id="msg" style="padding: 0px 10px;">{{ msg }}</p>
    {% endfor %}
  </div>
  {%block body%}
  <!-- Main Content Block with padding-top to avoid overlap -->
  <div class="main-content">
    {% block content %}{% endblock %}
  </div>
  {%endblock%}
  <!-- Scripts -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

  <!-- Messaging Script -->
  <script>
    let message = document.querySelector("#msg").innerHTML;
    if (message.length > 1) {
      $("#notification-container").addClass("notification");
      setTimeout(function() {
        $("#notification-container").remove();
      }, 5000);
    }

  </script>
</body>
</html>

WEB/templates/default_loading.html
{%extends 'load.html'%}

{%block load%}
<script>
    
    window.onload = function() {
        window.location.href = "{{ url_for('service.particular_searched_product') }}";
    };
</script>
{%endblock%}

WEB/templates/loginform.html
{%extends 'forms.html'%}
{% block title %}Login{% endblock %}
{%block form%}

<form id="loginForm" class="login-form active" method="POST" action="#">
    <input type="hidden" name="formType" value="login">
    <h3 id="form-title">Login</h3>
    <label for="username">Username:</label>
    <input type="text" id="username" name="username" value="{{username}}" placeholder="Enter Username" required>
    <label for="password">Password:</label>
    <input type="password" id="password" name="password" placeholder="Enter Password" required>
    <input type="submit" value="Submit" id="submit-btn">
    <a href="{{url_for('email.reg_email')}}">forget password?</a>
</form>

{%endblock%}

WEB/templates/profile.html
{%extends 'home.html'%}
{% block title %}Profile page{% endblock %}
{%block profile%}

<div class="container">
  <div class="col-lg-4">
    {%if photo != 'empty'%}
    <img src='{{url_for("static", filename = photo)}}' alt="" width="300" height="300" class="rounded-circle" style="object-fit: cover;">
    {%else%}
    <img src="{{url_for('static', filename = 'images/download.png')}}" alt="" alt="" width="300" height="300" class="rounded-circle" style="object-fit: cover;">
    {%endif%}
    <h2 class="fw-normal">{{username}}</h2>
    <h6>{{email}}</h6>
    <a href="{{url_for('home.delete_dp')}}" class="btn btn-outline-primary btn-sm px-4 gap-3">Remove Picture</a>
  </div>
 

  <form id="registerForm" class="login-form" method='post' enctype="multipart/form-data">
    <h3 id="form-title">Update user details</h3>
    <label for="username">Username:</label>
    <input type="text" id="username" name="username" placeholder="Enter Username" required value="{{username}}" style="color: black; justify-self: center;">
    <label for="email">Email:</label>
    <input type="email" id="email" name="email" placeholder="Enter Email" required value="{{email}}" style="color: black; justify-self: center;">
    <label for="phone">Phone Number:</label>
    <input type="phone" id="phone" name="phone" placeholder="Enter Phone Number" required value="{{phone}}" style="color: black; justify-self: center;">
    <label for="file" class="form-label">Upload profile picture:</label>
    <input type="file" name="profile_photo" class="form-control form-control-sm" style="width: 250px; margin-bottom: 10px;">
    <input type="submit" value="Update" class="btn btn-outline-primary btn-sm px-4 gap-3" style="width: 250px; justify-self: center;">
</form>
</div>


{%endblock%}

WEB/templates/view_cart.html
{%extends 'home.html'%}
{%block profile%}

<div class="container" style="margin-top: 70px;">
    <div class="row mb-2">
    {%for items in cart%}
    
    <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <h3 class="mb-0">{{items.price}}</h3>
          <div class="mb-1 text-body-secondary">{{items.date.strftime('%c')}}</div>
          <p class="mb-auto">{{items.product_name}}</p>
          <div class="d-grid gap-2 d-sm-flex justify-content-sm-center" style="margin-top: 5px;">
            <a href="{{url_for('service.view_product',name=items.product_name.replace('/', '_'))}}" type="button" class="btn btn-outline-primary px-4 gap-3">View<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-binoculars" viewBox="0 0 16 16">
              <path d="M3 2.5A1.5 1.5 0 0 1 4.5 1h1A1.5 1.5 0 0 1 7 2.5V5h2V2.5A1.5 1.5 0 0 1 10.5 1h1A1.5 1.5 0 0 1 13 2.5v2.382a.5.5 0 0 0 .276.447l.895.447A1.5 1.5 0 0 1 15 7.118V14.5a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 14.5v-3a.5.5 0 0 1 .146-.354l.854-.853V9.5a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v.793l.854.853A.5.5 0 0 1 7 11.5v3A1.5 1.5 0 0 1 5.5 16h-3A1.5 1.5 0 0 1 1 14.5V7.118a1.5 1.5 0 0 1 .83-1.342l.894-.447A.5.5 0 0 0 3 4.882zM4.5 2a.5.5 0 0 0-.5.5V3h2v-.5a.5.5 0 0 0-.5-.5zM6 4H4v.882a1.5 1.5 0 0 1-.83 1.342l-.894.447A.5.5 0 0 0 2 7.118V13h4v-1.293l-.854-.853A.5.5 0 0 1 5 10.5v-1A1.5 1.5 0 0 1 6.5 8h3A1.5 1.5 0 0 1 11 9.5v1a.5.5 0 0 1-.146.354l-.854.853V13h4V7.118a.5.5 0 0 0-.276-.447l-.895-.447A1.5 1.5 0 0 1 12 4.882V4h-2v1.5a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5zm4-1h2v-.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5zm4 11h-4v.5a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5zm-8 0H2v.5a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5z"/>
            </svg></a>

            <a href="{{url_for('service.buy', tobuy =items['product_name'].replace('/', '_'))}}" type="button" class="btn btn-outline-success px-4 gap-3">Buy now</a>

            <a href="{{url_for('service.delete_product', ID=items.id)}}" type="button" class="btn btn-outline-danger btn-sm px-4">Remove from Cart <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
              <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5m-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5M4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06m6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528M8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5"/>
            </svg></a>
          </div>
        </div>
        <div class="col-auto d-none d-lg-block">
          <img src="{{items.image}}" alt="" width="120" height="120">
        </div>
      </div>
    </div>
    {%endfor%}
  </div>
</div>

{%endblock%}